openapi: 3.0.3
info:
  title: 'Shopping List API'
  description: 'Defines the Shopping List API'
  version: 1.0.0
servers:
  - url: http://{host}:{port}/{basePath}
    description: The local development API server
    variables:
      host:
        default: localhost
        description: The local host
      port:
        enum:
          - '8080'
          - '8081'
        default: '8080'
      basePath:
        default: v1
tags:
  - name: ShoppingList
    description: Operations related to shopping lists
paths:
  /shopping-lists:
    post:
      tags:
        - ShoppingList
      summary: Creates a new shopping list resource
      description: Creates a new shopping list resource
      operationId: createShoppingList
      requestBody:
        description: The body of this POST request to create a new shopping list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShoppingList'
        required: true
      responses:
        201:
          description: The shopping list has been created
          content:
            application/json:
              schema:
                type: object
#                $ref: '#/components/schemas/ShoppingList'
    get:
      tags:
        - ShoppingList
      summary: Get all the shopping lists
      description: Get all the shopping lists
      operationId: allShoppingLists
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShoppingList'
  /shopping-lists/{id}:
    get:
      tags:
        - ShoppingList
      summary: Get a shopping list
      description: Get a shopping list
      operationId: getShoppingListById
      parameters:
        - name: id
          in: path
          description: The id of the shopping list
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ShoppingList'
  /shopping-lists/{id}/items:
    get:
      tags:
        - ShoppingList
      summary: Get all items from the shopping list
      description: Get all items from the shopping list
      operationId: getItemsForShoppingList
      parameters:
        - name: id
          in: path
          description: The id of the shopping list
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
  /items:
    post:
      tags:
        - Item
      summary: Createa a new item resource
      description: Createa a new item resource
      operationId: createItem
      requestBody:
        description: The body of this POST request to create a new item
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        201:
          description: The item has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    get:
      tags:
        - Item
      summary: Get all the items
      description: Get all the items
      operationId: allItems
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      tags:
        - Item
      summary: Get an item
      description: Get an item
      operationId: getItemById
      parameters:
        - name: id
          in: path
          description: The id of the item
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    ShoppingList:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Item:
      type: object
      required:
        - name
        - quantity
        - measurement
        - language
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        quantity:
          type: integer
          format: int64
        measurement:
          enum:
            - g
            - kg
            - l
            - pc
        language:
          enum:
            - en
            - de
            - ro
