openapi: 3.0.0
info:
  title: 'Shopping List API'
  description: 'Defines the Shopping List API'
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /shopping-lists:
    post:
      summary: Creates a new shopping list resource
      description: Creates a new shopping list resource
      operationId: createShoppingList
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ShoppingList'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
components:
  schemas:
    ShoppingList:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

